### PR TITLE
fix: build on rustc 1.94 and newer

### LINKED ISSUE #122: Build Error E0275
```
   Compiling weechat-matrix v0.1.0 (/src/weechat-matrix-rs)                                                                                                    
error[E0275]: overflow evaluating the requirement `(std::string::String, matrix_sdk::encryption::vodozemac::olm::DecryptionError): std::marker::Send`                                 
    --> src/connection.rs:128:17                                                                                                                                                      
     |                                                                                                                                                                                
 128 |         runtime.spawn(Connection::sync_loop(                                                                                                                                   
     |                 ^^^^^                                                                                                                                                          
     |                                                                                                                                                                                
     = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`matrix`)                   
```

### PR DESCRIPTION
**Pull request by toothrot**
The default compile time recursion_limit was lowered, and matrix-sdk depends on higher limits.

Fixes poljar/weechat-matrix-rs#122

### CODE REVIEW

**Comment by strk** [comment]
Thanks for this patch. With this I'm able to build on Debian 13 - using rustc 1.96.0 (ac68faa20 2026-05-25)
